;//Alias header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2014/8/11 8:18:35

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

IDH_1000=Á·Ï°.html	; Document
IDH_1001=¸ÖÇÙ - 01.html	; é’¢ç´1
IDH_1002=¸ÖÇÙ - 02.html	; é’¢ç´2
IDH_1003=¸ÖÇÙ - ³õ¼¶.html	; é’¢ç´æ›²
