;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2014/8/11 8:18:35

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1000	1000	; Document Á·Ï°.html
#define IDH_1001	1001	; é’¢ç´1 ¸ÖÇÙ - 01.html
#define IDH_1002	1002	; é’¢ç´2 ¸ÖÇÙ - 02.html
#define IDH_1003	1003	; é’¢ç´æ›² ¸ÖÇÙ - ³õ¼¶.html
